#!/usr/bin/env bash
Usage() {
	echo 'NAME:' ; echo "   ${0##*\/} - pretty filesystem info"
	echo 'USAGE:' ; echo "   \` ${0##*\/} [-[havs]] [%path(s)...] \`"
	echo 'DESCRIPTION:'
	echo '   Generates an attractive aggregation of disk/mount-point information including:'
	echo '    %Device, %Mount-Point, %Size-Used, %Size-Available, and %Percentage-Used (courtesy of `df`)' 
	echo '   Ran with no input, it returns this information for "non-trivial" filesystems -'
	echo '    that is, it tries to ignore snap container mounts, boot partitions, tmpfs, and other noise.'
	echo '    This behavior can be supressed by using one of the `-a,--all,-v,--verbose` flags.'
	echo '   If %[file]path(s) are supplied, the results will be limited to their corresponding filesystem (as with `df`).'
	echo 'OPTIONAL PARAMETERS:'
	echo -e "   -h,          : Show this message.\n    --help"
	echo -e "   -[av],       : Show all filesystem mounts\n    --all,\n    --verbose"
	echo '   -s,          : Include the size of %[file]path(s) (courtesy of `du`)'
	echo -e "    --size,              (ignored if none supplied).\n" ; exit ${1:-0}
}
for ((a=1;a<=$#;a++)); do
	case "${!a}" in
	\-[hH]|'--help') Usage ;;
	\-[aAvV]|'--all'|'--verbose') declare -gi All=1 ;;
	\-[sS]|'--size') Weight=true ;;
	*) [[ -e "${!a}" ]] && Item[${#Item[@]}]="$(df --output=source,file "${!a}" 2>/dev/null | awk '/^Filesystem/{ next; }; { print $1,$2 }')" || Usage 1
	esac
done

declare -gi W=$(( $(getSize x) - 8 ))
Prog() { { echo "scale=2; ${3:-100} * ($1 / $2)" | bc | cut -d\. -f1 ; } || echo '0' ; }
Spit() { ((P=${#4}+${#5}+1)) ; N=$(Prog $2 $1 $W) ; ((N<P?(X=P+N+${#4}+2):(X=0))) ; printf "\e[0;30m\u256D\e[9m%${W}s\e[29m\u256E\n\u251D\e[2;37m${4}\e[0;33m:\e[1;30m${5}\e[1;9;35m%$((X+N-P))s\e[2;34m%$((W-N-X))s\e[m\e[0;30m\u2525\e[1;30m${3}\u0025\n\e[0;30m\u2570\e[0;33m${7}\e[0;30m\e[9m%$((W-${#6}-${#7}))s\e[29;0;32m${6}\e[0;30m\u256F\e[0m\n%${W}s\r" ; }
GetDF() {
	while read Device Capacity SizeUsed SizeAvail PercUsed Mounted ; do
		(( ${#PercUsed} < (3 - All) )) || Spit "${Capacity//[!0-9\.\-]/}" "${SizeUsed//[!0-9\.\-]/}" "${PercUsed/\%/}" "${Device}" "${Mounted}" "$(echo "scale=2;${SizeAvail//[!0-9\.\-]/}/(10^6)" | bc -l)G" "$(echo "scale=2;${SizeUsed//[!0-9\.\-]/}/(10^6)" | bc -l)G"
	done < <(df -BK "${@}" 2>/dev/null | awk '/^Filesystem/{ next; }; {print $0}' )
}

if (( ${#Item[@]} == 0 )); then GetDF ; else
	while read line ; do
		[[ "${Mnt:-}" == "${line%%\ *}" ]] || GetDF "${line#*\ }"
		[[ ${Weight:-false} != true ]] || du -hs "${line#*\ }"
		Mnt="${line%%\ *}"
	done < <(for ((p=0;p<${#Item[@]};p++)); do echo "${Item[p]}" ; done | sort )
fi ; echo ""
