#!/usr/bin/env bash
[[ "$1" != +(\-)@([hH])?([eE][lL][pP]) ]] || {
    echo -e "NAME:\n   ${0##*\/} - read the fucking manual\n"
    echo -e "USAGE:\n   ${0##*\/} %(application name)s ...\n"
    echo 'DESCRIPTION:'
    echo '   First it converts the specified manpages into a pdf.'
    echo '   Then it tries to open said pdf in your prefered viewer.'
    echo -e '   (The generated pdf will be in ~/.rtfm/ )'"\n"
    exit 0
}
[[ -x $(which ps2pdf) ]] || { echo "Missing dependency: ps2pdf" ; exit 1 ; }
mkdir -p ${TFM:="${HOME:-/home/${USER:-$(whoami)}}/.rtfm"}
gtfm() {
    # {G}et {T}he {F}ucking {M}anual
    man -t "${1}" > "${1}.ps"
    [[ ! -s "${1}.ps" ]] || ps2pdf "${1}.ps" "${TFM}/${1}.pdf"
    rm "${1}.ps" 2>/dev/null
}
[[ -x ${PDF_VIEWER:="$(which $(xdg-mime query default application/pdf | cut -d\. -f1))"} ]] || PDF_VIEWER=less
[[ -e "${TFM}/${1}.pdf" ]] || gtfm "${1}"
[[ ! -s "${TFM}/${1}.pdf" ]] || (2>/dev/null ${PDF_VIEWER} "${TFM}/${1}.pdf" & )
