#!/usr/bin/env bash
[[ "$1" != +(\-)@([hH])?([eE][lL][pP]) ]] || {
	echo -e "NAME:\n   ${0##*\/} - count all the characters"
	echo -e "USAGE:\n   \`[ input... | ] ${0##*\/} [string(s), file(s), ...]\`"
	echo -e "DESCRIPTION:\n   Basically it's a more flexible \`wc -m\`\n"
	echo '   If input is supplied through a pipe, it counts the characters per line.'
	echo '   If input is a file, it counts the characters of all lines within said file.'
	echo "   Otherwise, (if input is a string), it counts it's characters."
	echo '  * Future versions may include similar -options to `wcl`,'
	echo '     but for now all counts are combined into a single sum total.'
	echo ""; exit 0
}
[ -t 0 ] || { while read line; do (( total += $(( $(echo "${line}" | wc -m) - 1 )) )) ; done < <(cat - ) ; }
for ((a=1;a<=$#;a++)); do
	if [[ -f "${!a}" ]]; then
		total[${#total[@]}]=$(( $(wc -m < "${!a}") - 1 ))
	else
		total[${#total[@]}]=$(( $(wc -m < <(echo "${!a}" )) - 1 ))
	fi
done
(( ${#total[@]} < 2 )) && echo "${total:-0}" || Sum ${total[@]}
