#!/usr/bin/env bash

### web2pdf, http2pdf, html2pdf

Usage() { echo -e "NAME:\n   ${0##*\/}\nUSAGE:\n   \` ${0##*\/}  [<'URL'>|-]  [<OUTPUT>|-] \`\n" ; exit ${1:-0} ; }
[[ "$1" != *(\-)@([hH])?([eE][lL][pP]) ]] || Usage

## check dependencies
for D in 'html2ps' 'ps2pdf' ; do [[ -x $(which $D) ]] || echo "${emsg[${#emsg}]:=Missing dependency:   $D}" ; done ; ((${#emsg[@]}==0)) || exit ${#emsg[@]}

for ((a=1;a<=$#;a++)); do
	case "${!a}" in
	\-[pPdD]|--path*|--dir*) mkdir -p ${OD:="${!a}"} ;;
	\-[oO]|--output*|--*[fn][ia][lm]e*) [[ "${!a}" == *\=* ]] || ((++a)) ; OF="${!a#*\=}" ;; 
	*) IO[${#IO[@]}]="${!a}"
	esac
done

### html2ps -T -u -U "$1" | ps2pdf - "${2:-${1##*\/}.pdf}"

#(( ${#IO[@]} + ${#OF} +))
#if [[ ${IO[0]} == "-" ]]; then
#	cat - | html2ps -T -u -U | ps2pdf - "${2:-${1##*\/}.pdf}"
#else

html2ps -T -u -U "$1" | ps2pdf - "${OD:-$PWD}/${OF:-${2:-${1##*\/}.pdf}}"
